### ISSUE TITLE
react 4.0.0 uploaded Aug 28, 2017?

### ISSUE THREAD

**Issue by jkleiser** [cleandart/react-dart#131]
This page https://pub.dartlang.org/packages/react#pub-pkg-tab-versions says that react 4.0.0 was uploaded Aug 28, 2017, while react 3.6.0 was uploaded Sep 18, 2017. It should probably have been the other way around.

**Comment by greglittlefield-wf** [comment]
There were a couple things we needed in the 3.x line (we couldn't move to 4.x yet), so we published 3.x releases with plans to also add that functionality to the 4.x line.

That's on my agenda this week; sorry I haven't gotten to it sooner
