### ISSUE TITLE
Performance? 

### ISSUE THREAD

**Issue by MartinOrtiz** [cleandart/react-dart#133]
I like React, I also like Dart.......

I was wondering about the performance of ReactNative+Dart VS ReactNative+JS

Of course, I know that Dart is converted to JS after all is said and done.....

But I was wondering if RN+Dart is performant with RN+JS? I am talking about any kind of significance hit. If one is slightly faster than the other, I don't care. 

I certainly would enjoy doing ReactNative with Dart

**Comment by greglittlefield-wf** [comment]
Unfortunately, this project doesn't integrate with ReactNative; it only supports server-side and client-side rendering of DOM. And in that regard, performance is slower than React with JS, but acceptable (see latest perf data in https://github.com/cleandart/react-dart/pull/95). 

If you're wanting to do something like ReactNative with Dart, then I think [Flutter](https://flutter.io/) is definitely worth looking into!

**Comment by MartinOrtiz** [comment]
Thanks for info...

I am looking at Flutter, and playing around with it a lot, and like it...

I am new to it, but one thing I am not sure about.....it has a React Native flavor to it, but I think it is inspired by React Native but it is NOT React Native???? 

I've been playing around with Flutter for the past two weeks, and still don't know the answer to that question....is it React Native + Dart???? 

For example in React Native, many of the React Native components map directly to their respective native counterparts....I am not sure if this is true for Flutter. React Native has support for most of the common components natively (that is, they map to the native controls on IOS and Android), and also have native support for GPS and Camera among other things....

So (you may or may not be able to answer this), is Flutter the same? Or is it a very fast rendering engine that mimics the native controls per device (iOS or Android), but does not map directly to them like React Native does....???

**Comment by greglittlefield-wf** [comment]
> Or is it a very fast rendering engine that mimics the native controls per device (iOS or Android), but does not map directly to them like React Native does....???

Yeah, that's correct. 

And it's still possible to access native APIs, though I'm not sure how it compares to React Native. More info on that in these links: 
- https://flutter.io/faq/#can-i-access-platform-services-and-apis-like-sensors-and-local-storage.
- https://flutter.io/platform-channels/ (this article has a great in-depth explanation)

**Comment by MartinOrtiz** [comment]
Thank you very much for all the helpful information!! 

Great links!

**Comment by greglittlefield-wf** [comment]
Sure thing, glad to help! 

Closing this issue since it seems that this project won't be able to help. Best of luck in the landscape of React-like frameworks for native apps, though! 😃
