### ISSUE TITLE
Cannot call setState() on component instance

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [cleandart/react-dart#28]
I'm trying to call setState on a component instance:

```dart
var myComponentInstance = MyComponent({'someProp': 'hello'}, [...]);

...

myComponentInstance.setState({'someProp': 'goodbye'});
```

This throws an error to the console:
```
Exception: Unhandled exception:
Class 'JsObject' has no instance method 'setState'.

NoSuchMethodError: method not found: 'setState'
Receiver: Instance of 'JsObject'
Arguments: [Instance of '_LinkedHashMap']
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
```

**Comment by hleumas** [comment]
@maxwellpeterson-wf you cannot call `setState` on the result of component factory. Component factory you created, `myComponentInstance`, is just descriptor saying to React, here should be that kind of component with these props. But you do not have an access to the component itself and can't call its methods. You can use setState only inside the component itself.
