### ISSUE TITLE
Any way to type a React Component for passing around in Dart code

### ISSUE THREAD

**Issue by trentgrover-wf** [cleandart/react-dart#35]
If I have created a react component in Dart via the normal mechanism:
```
var DynamoToolbar = react.registerComponent(() => new _DynamoToolbar());
class _DynamoToolbar extends react.Component {
```
and then want to keep track of a particular instance of that component in another Dart class via something like this:
```
import 'package:react/react.dart' as react;
import './dynamoToolbar.dart';

class DynamoModule {

  react.Component _toolbar;

  DynamoModule() {
    _toolbar = DynamoToolbar({});
  }
}
```
I get the following exception:
```
Exception: Uncaught Error: type 'JsObject' is not a subtype of type 'Component' of 'value'.
Stack Trace:
#0      DynamoModule._toolbar= (package:dynamo/dynamoModule.dart:15:19)
```
Is there any way to get this Dart type to work?  My code functions just fine if I revert to `var _toolbar;`, but I'm trying to be explicit with strong types everywhere I can.

**Comment by hleumas** [comment]
@trentgrover-wf call to `DynamoToolbar({})` does not create instance of `react.Component`. It is just some descriptor of component. React needs to create actual instance only if it realizes there are some differences in virtual dom.

**Comment by greglittlefield-wf** [comment]
Semi-related to this: we ran into a scenario in which we want to validate that a component is of a certain type. With the addition of `ReactComponentFactoryProxy`, this can now be achieved by comparing the `type` property of the JsObject with the `reactComponentFactory` on the component factory. (Similar to what's used in [react_test_utils.dart](https://github.com/cleandart/react-dart/blob/f253ea11f5df81a93c894dfaf5b1040b97add46d/lib/react_test_utils.dart#L34)).


```dart
import 'dart:js';
import 'package:react/react.dart' as react;
import './dynamoToolbar.dart';

/// Returns whether a component is an instance of the class corresponding to the specified component factory.
/// 
/// Similar to using `instanceof` in JS with React instances and ReactClass functions.
bool isInstanceOfComponent(JsObject instance, ReactComponentFactory componentFactory) {
  if (componentFactory == null || componentFactory is! ReactComponentFactoryProxy) {
    return false;
  }
  
  // Get the type of the instance, which may be a ReactClass JS function, or a String if it's a DOM component
  var instanceType = instance['type'];
  // Get the type of the component factory, a ReactClass JS function created within react-dart's registerComponent
  JsFunction jsComponentFactory = componentFactory.reactComponentFactory;
  JsFunction componentFactoryType = jsComponentFactory['type'];

  return instanceType == componentFactoryType;
}

class DynamoModule {

  JsObject _toolbar;

  DynamoModule() {
    _toolbar = DynamoToolbar({});

    assert(isInstanceOfComponent(_toolbar, DynamoToolbar)); // Passes
  }
}
```

This is a bit of a different use-case, but it's something.
