### ISSUE TITLE
SyntheticMouseEvent is missing `dataTransfer` property

### ISSUE THREAD

**Issue by evanweible-wf** [cleandart/react-dart#39]
Drag and drop mouse events have a `dataTransfer` property that can be used to access a `FileList` describing the files that may have been dropped onto an element. The `SyntheticMouseEvent` in React includes this information, but it's missing from the `SyntheticMouseEvent` class in this repo.

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

**Comment by hleumas** [comment]
@evanweible-wf thank you for pointing this out. Could you please prepare a patch?

**Comment by evanweible-wf** [comment]
https://github.com/cleandart/react-dart/pull/40

**Comment by hleumas** [comment]
@evanweible-wf Thank you for the patch! It is published on pub right now!
