### ISSUE TITLE
Example of TodoMVC with React-Dart ?

### ISSUE THREAD

**Issue by sethladd** [cleandart/react-dart#46]
Does this exist?

If not, where is the best example of React-Dart usage?

Thanks!

**Comment by hleumas** [comment]
Best example is currently the Readme. TodoMVC would be great, but does not exist yet.

**Comment by trentgrover-wf** [comment]
There's an oldish example here:
http://astashov.github.io/blog/2014/10/17/dart-apps-with-unidirectional-flow-and-persistent-data-structures/
https://github.com/astashov/todomvc/tree/master/labs/architecture-examples/react-dart-uniflow/web/dart

**Comment by tomaskulich** [comment]
There is also some example in /example directory. It's not a Todolist app, just a very simple frontend to Google Geocode service.
