### ISSUE TITLE
Styling example

### ISSUE THREAD

**Issue by johnmccutchan** [cleandart/react-dart#51]
I'm wondering if there are any samples in Dart that show styling?

**Comment by hleumas** [comment]
@johnmccutchan what's exactly on your mind? You can style your components using CSS styles. Or are you referring to something like this? https://speakerdeck.com/vjeux/react-css-in-js

**Comment by johnmccutchan** [comment]
I'm new to React (in general) so I'm just looking for some larger illustrative examples of React in Dart so I can get the flavour.

That CSS in JS talk was interesting, thanks.

**Comment by matystl** [comment]
currently you can use `className` and `style` property on components. . You may be interested to some articles to what is happening in javascript world with styling and react components but i am not aware that somehing similar is hapening in dart world:
https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284
https://github.com/js-next/react-style
https://github.com/jsstyles/jss
https://github.com/jsstyles/react-jss
