### ISSUE TITLE
Add cloneElement

### ISSUE THREAD

**Issue by hleumas** [cleandart/react-dart#52]
Moved from #47 discussion

**Comment by greglittlefield-wf** [comment]
Not sure how much work has been done on this, but I finalized a wrapper for `cloneElement` for usage in a project, with unit tests, if y'all are interested: https://gist.github.com/greglittlefield-wf/549ff3021624d7599492.

Feel free to incorporate any of that work. I'd also be more than happy to rework it into the `react_client.dart` code and PR it myself.

**Comment by aaronlademann-wf** [comment]
@trentgrover-wf @hleumas this issue can be closed.

**Comment by greglittlefield-wf** [comment]
@aaronlademann-wf This actually still hasn't been implemented in `react-dart`; only in one of our projects.

I'll plan on making a PR to implement this.
