### ISSUE TITLE
Better error for forgotten setConfiguration call

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [cleandart/react-dart#54]
If the consumer forgets to call `setClientConfiguration()` or `setServerConfiguration()` the error looks something like this:

```
The null object does not have a method 'call'.

  NoSuchMethodError: method not found: 'call'
  Receiver: null
  Arguments: [Closure: () => dynamic]
```

It would be great to have a more descriptive error when this happens, if at all possible. I will look into contributing this if no one has any immediate ideas for improvement.

**Comment by hleumas** [comment]
@maxwellpeterson-wf Thanks for suggestion! This would really be helpful. It would be awesome if you could provide some patch!

**Comment by aaronlademann-wf** [comment]
@maxwellpeterson-wf - @clairesarsam-wf implemented this as part of her work to upgrade to ReactJS `0.14.x` (#86) - https://github.com/cleandart/react-dart/pull/86/files#diff-73103ae4da65e607707d6ee86ee1d171R358

@trentgrover-wf I believe this issue can be closed.
