### ISSUE TITLE
isMounted

### ISSUE THREAD

**Issue by jonaskello** [cleandart/react-dart#56]
Is there a way to check isMounted? Specifically I am trying to follow the pattern where you check isMounted to determine if the result of an async call should handled, as documented [here](https://facebook.github.io/react/tips/initial-ajax.html). I could not find isMounted, either I am looking in the wrong place or it is not exposed to Dart?

**Comment by matystl** [comment]
You can use better pattern. I will asume that your ajax library return Future than you can do this:
```
StreamSubsctiption initialLoad;
componentDidMount() {
  inialLoad = ajaxCallReturningFuture(...).asStream().listen((val) {
     //setState or anything what you want to do with result of ajax call
  })
}
componentWillUnmount() {
  // clear all subsctiption you make
  // as future return only one value your code has already been called
  // or will not be called anymore so you cleand up everything 
  initialLoad.cancel();
}
```
That way you are not relying that code inside parsing result of ajax have to check if comoponent is still mounted or not.

**Comment by jonaskello** [comment]
You're absolutely right. This pattern is much better. In fact I'm already using a subscription like this. I guess I was just to tired to realize that the isMounted check becomes redundant in this case. Thanks for setting me straight :-).
