### ISSUE TITLE
Flux pattern

### ISSUE THREAD

**Issue by trentgrover-wf** [cleandart/react-dart#68]
We've got a reflux (https://github.com/reflux/refluxjs) like implementation of the Flux pattern in Dart that we're open sourcing (1.0 pub release in the next couple of days):
https://github.com/Workiva/w_flux

Any interest in mentioning it in your readme somewhere?

Do react-dart users have other pattern libs that they're using?

**Comment by maxwellpeterson-wf** [comment]
+1
