### ISSUE TITLE
Js bindings with new js-interop module

### ISSUE THREAD

**Issue by Aetet** [cleandart/react-dart#73]
After 1.13 dart-lang release, there's new js interop API - https://pub.dartlang.org/packages/js . It will be more handy to use this API.

**Comment by danschultz** [comment]
I've created an experimental package to test out the new `@JS` interop and React. If you're interested, you can check out the package here: https://github.com/danschultz/react.dart.

**Comment by johnbland-wf** [comment]
1.13 is released.

**Comment by aaronlademann-wf** [comment]
@Aetet check out #88

**Comment by aaronlademann-wf** [comment]
@Aetet @danschultz react-dart now uses the new `@JS` interop (via merge of #88).

@trentgrover-wf this issue can be closed.
