### ISSUE TITLE
Upgrade to v0.14.x of React JS

### ISSUE THREAD

**Issue by greglittlefield-wf** [cleandart/react-dart#79]

**Comment by clairesarsam-wf** [comment]
One of the major changes to [ReactJS 0.14](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#major-changes) is the separation of the API into two packages, `react` and `react-dom`. In upgrading, `react-dart` will either need to mirror that division or keep the same API it has currently.

In the first scenario, `react.dart` would split into `react.dart`, and `react_dom.dart` (containing `render`, `unmountComponentAtNode`, `findDOMNode`, `renderToString`, and `renderToStaticMarkup`). We could deprecate those methods in `react.dart` for a time, to give consumers a period to update their usages. For that period, we would still use `ReactDOM` under the hood for those methods in `react_client.dart` - consumers would receive only Dart deprecation warnings, not the ReactJS deprecation warnings.

In the second scenario, we would simply update `react_client.dart` to use `ReactDOM` appropriately. The top-level API for `react-dart` would not change.

The first option has the advantage of remaining closer to the ReactJS api. This could be useful for future upgrades and for not confusing consumers who are familiar with/referencing documentation for ReactJS.

The second option does not require consumers to update their API usage, and would keep the upgrade in `react-dart` simple.

**Comment by trentgrover-wf** [comment]
I would vote for the first scenario with an interim deprecation period.

If it's possible to introduce the new API while also maintaining a deprecated, but still backward compatible version of the API, we'd get the best of both worlds

**Comment by maxwellpeterson-wf** [comment]
I agree with Trent, the first option sounds good.

**Comment by greglittlefield-wf** [comment]
First option sounds good to me as well—keeping a deprecated version of the old API will make the upgrade go a lot smoother.

**Comment by greglittlefield-wf** [comment]
Note that `renderToString`/`renderToStaticMarkup` should probably go into a separate library, like `react_dom_server.dart`. (See [ReactDOMServer](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver).)

**Comment by travissanderson-wf** [comment]
+1

**Comment by clairesarsam-wf** [comment]
Thanks for the input everybody, splitting into separate libraries overlapped with a deprecation period it is. :+1:

**Comment by aaronlademann-wf** [comment]
@trentgrover-wf this issue can be closed.
